OrdererOrgs:
  - Name: OrdererOrg
    Domain: ordererorg-f-1
    Template:
      Count: 1
    Type: solo

PeerOrgs:
  - Name: Org1
    Domain: org1-f-1
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2-f-1
    Template:
      Count: 2
    Users:
      Count: 1


Kafka:
  - IP: 
  - IP: 
