apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{resourcesName}}
spec:
    capacity:
       storage: 500Mi
    accessModes:
       - ReadWriteMany
    nfs:
      path: /opt/share/resources
      server: {{nfsServerIP}}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: {{namespace}}
    name: {{resourcesName}}
spec:
   accessModes:
     - ReadWriteMany
   resources:
      requests:
        storage: 10Mi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   namespace: {{namespace}}
   name: {{name}}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
       app: cli
    spec:
      containers:
        - name: {{name}}
          image:  hyperledger/fabric-tools:x86_64-1.0.5
          imagePullPolicy: Never
          env:

          - name: CORE_PEER_TLS_ENABLED
            value: "false"
          - name: CORE_PEER_TLS_CERT_FILE
            value: /etc/hyperledger/fabric/tls/server.crt
          - name: CORE_PEER_TLS_KEY_FILE
            value: /etc/hyperledger/fabric/tls/server.key
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: /etc/hyperledger/fabric/tls/ca.crt
          - name: CORE_VM_ENDPOINT
            value: unix:///host/var/run/docker.sock
          - name: GOPATH
            value: /opt/gopath
          - name: CORE_LOGGING_LEVEL
            value: DEBUG
          - name: CORE_PEER_ID
            value: {{name}}
          - name: CORE_PEER_ADDRESS
            value: {{peerAddress}}
          - name: CORE_PEER_LOCALMSPID
            value: {{mspid}}
          - name: CORE_PEER_MSPCONFIGPATH
            value: /etc/hyperledger/fabric/msp
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          volumeMounts:
           - mountPath: /host/var/run/
             name: run
          # when enable tls , should mount orderer tls ca
           - mountPath: /etc/hyperledger/fabric/msp
             name: certificate
             subPath: {{mspPath}}
           - mountPath: /etc/hyperledger/fabric/tls
             name: certificate
             subPath: {{tlsPath}}
           - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/resources/channel-artifacts
             name: resources
             subPath: channel-artifacts
      volumes:
        - name: certificate
          persistentVolumeClaim:
              claimName: {{pvName}}
        - name: resources
          persistentVolumeClaim:
              claimName: {{resourcesName}}
        - name: run
          hostPath:
            path: /var/run
